version: "3.9"

services:
  postgres:
    image: postgres:14.3-alpine3.16
    container_name: postgres-p-5432
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-p-80
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "80:80"
    depends_on:
      - postgres
